### PingPong
# Checks the server health and its version.
GET http://{{host}}/ping


### PackageTrack
# Get the tracking history of a package.
GET http://{{host}}/track/{{carrier_id}}/{{tracking_code}}


### UserRegister
# Registers the user in the database.
POST http://{{host}}/register
Content-Type: application/x-www-form-urlencoded

username = {{username}} &
password = {{password}}


### UserLogin
# Logs the use into the system.
POST http://{{host}}/login
Content-Type: application/x-www-form-urlencoded

username = {{username}} &
password = {{password}}


### UserLogout
# Logs the user out of the system.
GET http://{{host}}/logout


### FavoritePackage
# Marks a tracked package as favorite.
POST http://{{host}}/favorite/{{carrier_id}}/{{tracking_code}}
Content-Type: application/x-www-form-urlencoded

name = {{parcel_name}}


### FavoritePackageByID
# Marks a tracked package as favorite using its ID.
POST http://{{host}}/favorite/1
Content-Type: application/x-www-form-urlencoded

name = {{parcel_name}}


### UnfavoritePackage
# Removes a tracked package from the favorites.
DELETE http://{{host}}/favorite/{{carrier_id}}/{{tracking_code}}


### UnfavoritePackageByID
# Removes a tracked package from the favorites using its ID.
DELETE http://{{host}}/favorite/1


### ListUserPackages
# Lists all of the user's tracked packages.
GET http://{{host}}/parcels
