### PingPong
# Checks the server health and its version.
GET http://{{host}}/ping


### PackageTrack
# Get the tracking history of a package.
GET http://{{host}}/track/{{carrier_id}}/{{tracking_code}}
X-Auth-Token: {{username}}:{{auth_token}}


### UserRegister
# Registers the user in the database.
POST http://{{host}}/register
Content-Type: application/x-www-form-urlencoded

username = {{username}} &
password = {{password}}


### AuthTokenGenerate
# Generates a new authentication token for the user.
POST http://{{host}}/auth/token/new
Content-Type: application/x-www-form-urlencoded
X-Auth-Token: {{username}}:{{password}}

description = PyCharm HTTP Request


### AuthTokenRevoke
# Revokes one of the authentication tokens of the user.
DELETE http://{{host}}/auth/token/{{auth_token}}
X-Auth-Token: {{username}}:{{auth_token}}


### FavoritePackage
# Marks a tracked package as favorite.
POST http://{{host}}/favorite/{{carrier_id}}/{{tracking_code}}
Content-Type: application/x-www-form-urlencoded
X-Auth-Token: {{username}}:{{auth_token}}

name = {{parcel_name}}


### FavoritePackageByID
# Marks a tracked package as favorite using its ID.
POST http://{{host}}/favorite/{{parcel_id}}
Content-Type: application/x-www-form-urlencoded
X-Auth-Token: {{username}}:{{auth_token}}

name = {{parcel_name}}


### UnfavoritePackage
# Removes a tracked package from the favorites.
DELETE http://{{host}}/favorite/{{carrier_id}}/{{tracking_code}}
X-Auth-Token: {{username}}:{{auth_token}}


### UnfavoritePackageByID
# Removes a tracked package from the favorites using its ID.
DELETE http://{{host}}/favorite/{{parcel_id}}
X-Auth-Token: {{username}}:{{auth_token}}


### MarkDelivered
# Flags a favorite parcel as delivered.
POST http://{{host}}/deliver/{{parcel_id}}
X-Auth-Token: {{username}}:{{auth_token}}


### MarkNotDelivered
# Flags a favorite parcel as not delivered.
DELETE http://{{host}}/deliver/{{parcel_id}}
X-Auth-Token: {{username}}:{{auth_token}}


### ListUserPackages
# Lists all of the user's tracked packages.
GET http://{{host}}/parcels
X-Auth-Token: {{username}}:{{auth_token}}
