---
db:
  host: 'localhost'
  database: 'openparcel'
  username: 'openparcel'
  password: 'OpenParcel@2024'
  pool_size: 8
app:
  cache:
    refresh_timeout: 1800
  scraper:
    max_instances: 30
  allow_registration: true
  request_bundle_key: 'please change me'
proxy:
  use_proxies: false
  api_keys:
    pubproxy: 'delete this line if not using PubProxy'
    proxifly: 'delete this line if not using Proxifly'
    openproxyspace: 'delete this line if not using Open Proxy Space'
    webshare: 'delete this line if not using WebShare'
