---
SECRET_KEY: 'please change me'
DEBUG: true
DB_HOST: 'openparcel.db'
CACHE_REFRESH_TIMEOUT: 1800
ALLOW_REGISTRATION: true
PUBPROXY_API_KEY: 'delete this line if not using PubProxy'
PROXIFLY_API_KEY: 'delete this line if not using Proxifly'
OPENPROXYSPACE_API_KEY: 'delete this line if not using Open Proxy Space'
WEBSHARE_API_KEY: 'delete this line if not using Open Proxy Space'
