---
SECRET_KEY: 'please change me'
DEBUG: true
DB_HOST: 'localhost'
DB_DATABASE: 'openparcel'
DB_USER: 'dbuser'
DB_PASS: 'dbpassword'
DB_POOL_SIZE: 8
CACHE_REFRESH_TIMEOUT: 1800
ALLOW_REGISTRATION: true
MAX_SCRAPER_INSTANCES: 30
REQ_BUNDLE_KEY: 'please change me'
PUBPROXY_API_KEY: 'delete this line if not using PubProxy'
PROXIFLY_API_KEY: 'delete this line if not using Proxifly'
OPENPROXYSPACE_API_KEY: 'delete this line if not using Open Proxy Space'
WEBSHARE_API_KEY: 'delete this line if not using Open Proxy Space'
